### PR TITLE
Suggestions-for-X-Max3

### PR DESCRIPTION
**Pull request by hcrohland**
A few improvements I made to printer.cfg and macros.cfg:

### CODE REVIEW

**Comment by Phil1988** [comment]
Thanks @hcrohland for your suggestions.

The bed position should be changed for all printers at the point where you suggested plus one more.
I will add this soon - Thanks.

The 
```
[temperature_fan board_fan]
pin:PC4
```
Cant be included for all (see https://github.com/Phil1988/FreeDi/wiki/Why-creating-a-backup-is-important#example-differences
This is why every user should do a backup first and then refer to this: https://github.com/Phil1988/FreeDi/wiki/Post-install-and-config-section#fans

I will have a look at your M191 suggestion, as I am also using orca right now and had no issues on a X-Max 3 so far.

**Comment by Phil1988** [comment]
I changed the macro based on your suggestion to this:
```
# Chamber heater macro
[gcode_macro M191]
gcode:
    {% set s = params.S|float %}
	SET_HEATER_TEMPERATURE HEATER=chamber_heater TARGET={s}
    {% if s == 0 %}
        M117 Chamber heater off
    {% else %}
        TEMPERATURE_WAIT SENSOR="heater_generic chamber_heater" MINIMUM={s-1} MAXIMUM={s+1}
        M117 Chamber at target temperature
  {% endif %}
```

Improvement: The chamber is set to off, when the slicer commands it
The `M140 S90` was removed because under normal circumstances the bed always helps heating as it is turned on previously.

Thanks for your help!

**Comment by hcrohland** [comment]
IMHO it would be better to have the boardfan included - maybe commented out - and add a note in the installation guide to adjust it accordingly. See #26

**Comment by Phil1988** [comment]
I respect your opinion and thought about that already, but I decided against it.

If its included that way, the logic would be to have all the possibilities in the config and commented out.
This would be a mess with all combinations (inductive probe/bltouch, different fans, different toolheads, different motors, different stepper drivers, etc). 
And its almost impossible as Qidi did so many unpublished chages.

I also dont want to make it look as its all complete out of the box. 
Each user should get used to compare my generic config with their unique config and doing changes accordingly.
I dont only have a "note" at the guide, but a complete page dedicated to the possible changes that I am aware of :)
**Reading the wiki is important.** (at least the while "Installation guide" section should be read once)
I hope you understand that logic and my goal.

**Comment by hcrohland** [comment]
I did read about the different mainboards and the whole installation guide. But I missed the connection. Only when running the print bed into the nozzle I started digging into printer.cfg and did a side-by-side comparison.

Especially for someone new to the printer and/or klipper it is very difficult to understand what to look for.

Don't get me wrong: I am not critizing your work. It is greatly appreciated. I only want to make everybody's life (including yours) easier by guiding people in the right direction.

**Comment by Phil1988** [comment]
Dont get me wrong: Critizizing my work is good for improvements ;)

Including this section applies to you and fraction of users.
That will justify putting every config possible into the printer section but commented out.
Even more: If I open that door, I need to include every config because of consistency.

This will lead into a messed printer.cfg and will not help users who dont look at the config and compare at all.

Besides that I would still need to maintain the wiki because of new config sections / changed hardware components.
I am open for a nice solution that help users, leave a clean config and dont put unnecessary work on my side.
Currently I dont see it.
So what is your suggestion on this?

**Comment by hcrohland** [comment]
What about adding the following to https://github.com/Phil1988/FreeDi/wiki/Installation-guide-for-fresh-systems

````
<br/>

# Adjust the printer configuration to your specific board

Open the printer.cfg and compare it to your backup version. 
It might be missing some fan entries. E.g. it does not include the board fan (mistyped in the Qidi config as borad_fan)

Here is an config section which will tune the fan according to mainboard temperature. The Qidi default runs it at full speed all the time :

` ```
[temperature_fan board_fan]
pin:PC4
max_power: 1.0
kick_start_time: 0.5
sensor_type: temperature_host
control: pid
pid_Kp: 4
pid_Ki: 1 
pid_Kd: 1
target_temp:48
min_temp: 0
max_temp: 80
min_speed: 0
off_below: 0.3
` ```

But your board might have that on another pin and need to have other settings. So to be on the safe side use the section "[heater_fan borad_fan]" from your backup cfg.

Another missing entry might be the "[heater_fan hotend_fan2]" section.
````

I like the additional feature of configuring the board fan as a temperature_fan. But I understand if you do not want to include it. Then I would include the hint to look for the board and secondary heater fan.

**Comment by Phil1988** [comment]
I added a hint "chapter" in the install guide based on your suggestion here:
https://github.com/Phil1988/FreeDi/wiki/Installation-guide-for-fresh-systems#adjust-the-printer-configuration-to-your-specific-hardware

I also took this as an occasion to change the 
[Post-install-and-config-section](https://github.com/Phil1988/FreeDi/wiki/Post-install-and-config-section)

**Comment by hcrohland** [comment]
Nice.

One final nitpick: I would move that paragraph after "Open the Mainsail UI of your printer with a browser by entering the printer's IP address.
Don't use the modified port (10088) that you might know from the stock machine.
Then go to the "MACHINE" section:"

**Comment by Phil1988** [comment]
I integrated better now I think, have a look at the latest changes and thanks for your opinions and support !

**Comment by hcrohland** [comment]
Nice!

Reach out to me if I can help in any way in the future.

Cheers and Happy New Year,
Christoph

**Comment by Phil1988** [comment]
Happy New Year and sorry for the late reply. 
Worked hard to get that v1.30 done.

> IMHO it would be better to have the boardfan included - maybe commented out - and add a note in the installation guide to adjust it accordingly. See #26

I changed my mind and integrated everything that will not cause issues but might be too much into the configs.

This applies to the full images and the published configs at the [config section](https://github.com/Phil1988/FreeDi/tree/master/config_section).

For easier use, I integrated "heads up markers" in the given configs.
They start by `#!#` for an easy search and find.
Eg:
```
#!# Pay attention to this section and compare it with your stock backup config
[probe]
pin: ^!MKS_THR:gpio21
x_offset: 28
y_offset: 4.4
z_offset: 1.549
speed: 5
samples: 2
samples_result: average
sample_retract_dist: 0.7
samples_tolerance: 0.08
samples_tolerance_retries:3

[...]

[tmc2209 extruder]
uart_pin: MKS_THR:gpio6
interpolate: True
run_current: 0.714              #!# Pay attention to this value and compare it with your stock backup config
stealthchop_threshold: 0
```

This and more at the [latest release v1.30](https://github.com/Phil1988/FreeDi/releases/tag/v1.30)

**Pull request closed without merging**
